### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [moabdali/MegaCheckers#2]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPLv3 or AGPLv3 license so that others are encouraged to contribute changes back to your project.

**Comment by moabdali** [comment]
Thanks for the heads up.  I'll have to read up on the different licenses and see what my options are on the offhand chance that one day I get good at programming and decide to create an app for release on mobile.

For now I do want people to to enjoy this game and make their own changes and whatnot, but I wanna keep the option to distribute it in the late future as a playstore game.

**Comment by TechnologyClassroom** [comment]
Those licenses are compatible with playstore.

**Comment by moabdali** [comment]
Alright, I've added the license. Thanks for the email and tips.
